services:
  studyapp:
    container_name: study-app
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/ash -c "npm run dev"
    ports:
      - 3005:3005
    volumes:
      - .:/myapp
      - /myapp/node_modules
    networks:
      - study_network
    labels:
      - 'traefik.frontend.rule=Host:localhost'
      - 'traefik.frontend.priority=1'
      - 'traefik.basic.port=3005'
    extra_hosts:
      - 'docker.localhost:host-gateway'

networks:
  study_network:
    external: true
